### ISSUE TITLE
How to preprocess my own corpus?

### ISSUE THREAD

**Issue by shizhediao** [moonlightlane/QG-Net#6] opened 2019-02-25 06:59 UTC
Thanks for your great work!
I found that your model is trained on SQuAd dataset.
I was wondering could I train a model with my own dataset?
Thanks!

**Comment by zichaow** [comment] 2020-02-20 02:44
Hi, extremely sorry for late reply... not sure if this still helps but maybe Duplicate of #3 ?

**Closed as completed** 2020-03-03 04:55 UTC
